[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
address = "0.0.0.0"

[theme]
primaryColor = "#667eea"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
font = "sans serif"


